### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by LinuxFO** [fonline-roleplay/FO4RP#107]
Hello, where can I download client?

**Comment by APAmk2** [comment]
Hello, [here ](https://discord.gg/tqtaTjV4ky), but why you need this? We're not providing any support to forks, and you don't looks like a player. You just forking servers for no reasons.

**Comment by LinuxFO** [comment]
Yes, I was not playing on this server (actually I was playing FOnline Reloaded few years ago). However is it possible to run your game localy? If it is not possible then I will delete my fork. Thanks.

**Comment by APAmk2** [comment]
Yes, it's possible, but need some work to make this works, i can't tell you all things, but the first problem you'll encounter is config, have fun.
